# Generated by Django 4.2.3 on 2025-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_habitude_categorie_habitude_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitude',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
